#!/bin/sh
echo "bootstrapping vim"

VIMPLUG_LOCAL="$HOME/.local/share/nvim/site/autoload/plug.vim"
if [ ! -d "$VIMPLUG_LOCAL" ]; then
  sh -c "curl -fLo $VIMPLUG --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
fi

if command -v vim >/dev/null 2>&1; then
  vim "+PlugUpdate" "+PlugClean!" "+PlugUpdate" "+qall"
fi

echo "vim bootstrap complete"
